---
- name: Notify and handler Example
  hosts: webservers
  become: yes                                                                        

  tasks:
    - name: Install Apache
      yum: 
        name: httpd
        state: present
      notify: restart apache service

    - name: copy custom index.html file
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
      notify: restart apache service

  handlers:
    - name: restart apache service
      service:
        name: httpd
        state: restarted
